name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  panoptica-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: my-image:latest
      - name: Install Panoptica CICD CLI
        run: |
          curl -O https://download.panoptica.app/panoptica-cicd/1.5.0/artifacts/linux-amd64/panoptica-cicd && chmod +x ./panoptica-cicd
      - name: Run image scan
        run: |
          ./panoptica-cicd image my-image:latest --local --report --policies=ci-cd-demo-rule --api-key=ODcyOTAwMzMtMzRkNS00M2U5LTlkZGEtMzk3ZDk3YWU0NWQwQGFrLmV0aWNsb3VkLmlvOmFHMmo5bWIoZnY+S0BAeDA6Q0E3OzZOcjE1VDE3LXV9Nj5QRmg+NEh2RSg7NTNiR0hAbDMpNzRXT1YsZG9Lei0=
  panoptica-iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Panoptica CICD CLI
        run: |
          curl -O https://download.panoptica.app/panoptica-cicd/1.5.0/artifacts/linux-amd64/panoptica-cicd && chmod +x ./panoptica-cicd
      - name: Run iac scan
        run: |
          ./panoptica-cicd iac . --report --policies=iac-demo-rule --api-key=ODcyOTAwMzMtMzRkNS00M2U5LTlkZGEtMzk3ZDk3YWU0NWQwQGFrLmV0aWNsb3VkLmlvOmFHMmo5bWIoZnY+S0BAeDA6Q0E3OzZOcjE1VDE3LXV9Nj5QRmg+NEh2RSg7NTNiR0hAbDMpNzRXT1YsZG9Lei0=
