name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  panoptica-cicd-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: my-image:latest
      - name: Install Panoptica CICD CLI
        run: |
          curl -O https://download.panoptica.app/panoptica-cicd/1.4.0/artifacts/linux-amd64/panoptica-cicd && chmod +x ./panoptica-cicd
      - name: Run image scan
        run: |
          ./panoptica-cicd image my-image:latest --local --report --api-key=MjY4ODIyYTQtYTk3Mi00YzJkLWIwMTEtMzM5ZjE3Nzg0ODA5QGFrLmV0aWNsb3VkLmlvOmg7WHItNXYhN0BWLTFocjtPMDhBLVlbZUU1YXRqYkQ5N3EsOjBGTDlCaSlFQys7NWs0OC1MQzBieyxEeGVSODI=